import { describe, expect, it } from 'vitest';
import { readAppConfig } from './config';

describe('readAppConfig', () => {
  it('parses typed values from env strings', () => {
    const config = readAppConfig({
      CANDLE_INTERVAL_MS: '60000',
      LOOKBACK_CANDLES: '5',
      BREAKOUT_LOOKBACK_CANDLES: '8',
      MIN_RETURN_PCT: '0.01',
      MIN_RANGE_PCT: '0.02',
      MIN_BODY_PCT: '0.03',
      MAX_WICK_TO_BODY_RATIO: '1.5',
      TAKE_PROFIT_PCT: '0.04',
      STOP_LOSS_PCT: '0.05',
      HOLD_CANDLES: '2',
      FEE_BPS: '7',
      SLIPPAGE_BPS: '3',
      INITIAL_EQUITY: '2500',
      POSITION_NOTIONAL: '100',
      BACKTEST_INPUT_FILE: 'data/input.jsonl',
      ENABLE_HOUR_FILTER: 'true',
      ALLOWED_ENTRY_HOURS_UTC: '8,13,21',
      ENABLE_TREND_FILTER: 'true',
      TREND_TIMEFRAME_MULTIPLIER: '4',
      TREND_LOOKBACK_CANDLES: '6',
      TREND_MIN_RETURN_PCT: '0.02',
      ALLOW_NEUTRAL_TREND: 'false',
      ENABLE_MIN_EDGE_FILTER: 'yes',
      MIN_EXPECTED_MOVE_PCT: '0.01',
      ENABLE_NET_RISK_REWARD_FILTER: 'true',
      MIN_NET_RISK_REWARD: '1.5',
      ENABLE_SAMPLE_COUNT_FILTER: '1',
      MIN_SAMPLES_PER_CANDLE: '12',
      ENABLE_BREAK_EVEN_EXIT: 'true',
      BREAK_EVEN_TRIGGER_PCT: '0.0017',
      BREAK_EVEN_EXIT_BUFFER_PCT: '0.0002',
      ENABLE_TRAILING_EXIT: 'yes',
      TRAILING_TRIGGER_PCT: '0.0021',
      TRAILING_DROP_PCT: '0.0007',
      ENABLE_DIRECT_BREAKOUT_ENTRY: 'false',
      ENABLE_IMPULSE_CONFIRMATION_ENTRY: 'true',
      ENABLE_IMPULSE_FADE_ENTRY: 'true',
      ENABLE_FOLLOW_THROUGH_CONFIRMATION: 'true',
      IMPULSE_MIN_RETURN_PCT: '0.011',
      IMPULSE_MIN_RANGE_PCT: '0.022',
      IMPULSE_MIN_BODY_TO_RANGE_RATIO: '0.66',
      IMPULSE_MAX_WICK_TO_BODY_RATIO: '1.4',
      IMPULSE_MAX_RETURN_PCT: '0.02',
      CONFIRMATION_MIN_RETURN_PCT: '0.003',
      CONFIRMATION_MIN_BODY_TO_IMPULSE_BODY_RATIO: '0.45',
      CONFIRMATION_MAX_WICK_TO_BODY_RATIO: '1.2',
      RECENT_RANGE_LOOKBACK_CANDLES: '7',
      MIN_RECENT_RANGE_AVG_PCT: '0.004',
      MIN_VOLATILITY_PCT: '0.006',
      MAX_CANDLE_GAP_MULTIPLIER: '4',
      MAX_HOLD_CANDLES: '3',
      ENABLE_LONG_ENTRIES: 'false',
      ENABLE_SHORT_ENTRIES: 'true',
    } as NodeJS.ProcessEnv);

    expect(config).toEqual({
      candleIntervalMs: 60000,
      lookbackCandles: 5,
      breakoutLookbackCandles: 8,
      minReturnPct: 0.01,
      minRangePct: 0.02,
      minBodyPct: 0.03,
      maxWickToBodyRatio: 1.5,
      takeProfitPct: 0.04,
      stopLossPct: 0.05,
      holdCandles: 2,
      feeBps: 7,
      slippageBps: 3,
      initialEquity: 2500,
      positionNotional: 100,
      backtestInputFile: 'data/input.jsonl',
      enableHourFilter: true,
      allowedEntryHoursUtc: [8, 13, 21],
      enableTrendFilter: true,
      trendTimeframeMultiplier: 4,
      trendLookbackCandles: 6,
      trendMinReturnPct: 0.02,
      allowNeutralTrend: false,
      enableMinEdgeFilter: true,
      minExpectedMovePct: 0.01,
      enableNetRiskRewardFilter: true,
      minNetRiskReward: 1.5,
      enableSampleCountFilter: true,
      minSamplesPerCandle: 12,
      enableBreakEvenExit: true,
      breakEvenTriggerPct: 0.0017,
      breakEvenExitBufferPct: 0.0002,
      enableTrailingExit: true,
      trailingTriggerPct: 0.0021,
      trailingDropPct: 0.0007,
      enableDirectBreakoutEntry: false,
      enableImpulseConfirmationEntry: true,
      enableImpulseFadeEntry: true,
      enableFollowThroughConfirmation: true,
      impulseMinReturnPct: 0.011,
      impulseMinRangePct: 0.022,
      impulseMinBodyToRangeRatio: 0.66,
      impulseMaxWickToBodyRatio: 1.4,
      impulseMaxReturnPct: 0.02,
      confirmationMinReturnPct: 0.003,
      confirmationMinBodyToImpulseBodyRatio: 0.45,
      confirmationMaxWickToBodyRatio: 1.2,
      recentRangeLookbackCandles: 7,
      minRecentRangeAvgPct: 0.004,
      minVolatilityPct: 0.006,
      maxCandleGapMultiplier: 4,
      maxHoldCandles: 3,
      enableLongEntries: false,
      enableShortEntries: true,
    });
  });

  it('falls back to defaults when env values are missing', () => {
    const config = readAppConfig({} as NodeJS.ProcessEnv);

    expect(config).toMatchObject({
      candleIntervalMs: 300000,
      lookbackCandles: 3,
      breakoutLookbackCandles: 3,
      minReturnPct: 0.001,
      minRangePct: 0.0008,
      minBodyPct: 0.0005,
      maxWickToBodyRatio: 2.5,
      takeProfitPct: 0.002,
      stopLossPct: 0.0015,
      holdCandles: 1,
      feeBps: 6,
      slippageBps: 2,
      initialEquity: 1000,
      positionNotional: 50,
      backtestInputFile: '',
      enableHourFilter: false,
      allowedEntryHoursUtc: [],
      enableTrendFilter: false,
      trendTimeframeMultiplier: 3,
      trendLookbackCandles: 3,
      trendMinReturnPct: 0.001,
      allowNeutralTrend: true,
      enableMinEdgeFilter: false,
      minExpectedMovePct: 0.001,
      enableNetRiskRewardFilter: false,
      minNetRiskReward: 1,
      enableSampleCountFilter: false,
      minSamplesPerCandle: 1,
      enableBreakEvenExit: false,
      breakEvenTriggerPct: 0.0016,
      breakEvenExitBufferPct: 0.0001,
      enableTrailingExit: false,
      trailingTriggerPct: 0.002,
      trailingDropPct: 0.0006,
      enableDirectBreakoutEntry: true,
      enableImpulseConfirmationEntry: false,
      enableImpulseFadeEntry: false,
      enableFollowThroughConfirmation: false,
      impulseMinReturnPct: 0.0012,
      impulseMinRangePct: 0.0018,
      impulseMinBodyToRangeRatio: 0.55,
      impulseMaxWickToBodyRatio: 1.5,
      impulseMaxReturnPct: Number.POSITIVE_INFINITY,
      confirmationMinReturnPct: 0.0004,
      confirmationMinBodyToImpulseBodyRatio: 0,
      confirmationMaxWickToBodyRatio: Number.POSITIVE_INFINITY,
      recentRangeLookbackCandles: 6,
      minRecentRangeAvgPct: 0.0012,
      minVolatilityPct: 0,
      maxCandleGapMultiplier: 3,
      maxHoldCandles: Number.POSITIVE_INFINITY,
      enableLongEntries: true,
      enableShortEntries: true,
    });
  });

  it('parses comma-separated UTC hours with leading zeroes into numbers', () => {
    const config = readAppConfig({
      ALLOWED_ENTRY_HOURS_UTC: '00,02,03,05,08,11,13,14,16,18,22,23',
    } as NodeJS.ProcessEnv);

    expect(config.allowedEntryHoursUtc).toEqual([
      0,
      2,
      3,
      5,
      8,
      11,
      13,
      14,
      16,
      18,
      22,
      23,
    ]);
    expect(config.allowedEntryHoursUtc.every((hour) => typeof hour === 'number')).toBe(true);
  });

  it('lets ALLOW_LONG and ALLOW_SHORT override legacy direction flags', () => {
    const config = readAppConfig({
      ALLOW_LONG: 'false',
      ALLOW_SHORT: 'true',
      ENABLE_LONG_ENTRIES: 'true',
      ENABLE_SHORT_ENTRIES: 'false',
    } as NodeJS.ProcessEnv);

    expect(config.enableLongEntries).toBe(false);
    expect(config.enableShortEntries).toBe(true);
  });
});
